### ISSUE TITLE
new PRESSING issue discovered

### ISSUE THREAD

**Issue by Sai-0903** [Sanjeb/Chat-app#2]
DISCARD doesn't automatically ban gay people. This is atrocious and must be fixed IMMEDIATELY, this is the most pressing issue of the decade and must be given appropriate attention by the creator, owner of discord

**Comment by Professional-Retard** [comment]
> DISCARD doesn't automatically ban gay people. This is atrocious and must be fixed IMMEDIATELY, this is the most pressing issue of the decade and must be given appropriate attention by the creator, owner of discord

Well said, my dear friend, I hope the creator of this chat app can cleanse his project of anti-social elements and get instant recognition from the board by providing the aforementioned cultured feature.

**Comment by Mulukulum** [comment]
I too was shocked to find the absence of any mention of Ayudha Puja in this app. Completely agree with @Professional-Retard that this is a matter worthy of attention from the board.

The Current UI Looks like this, with no culture to be found anywhere

![image](https://user-images.githubusercontent.com/114818131/204130854-787727c1-b535-4e23-bc9c-a58f1ac21b3b.png)
![image](https://user-images.githubusercontent.com
![image](https://user-images.githubusercontent.com/114818131/204130879-6ae80765-3f22-4fbc-a47a-c3de57af5d44.png)
/114818131/204130867-98632700-a5c3-4bc5-a91a-5a16403a7088.png)
