### ISSUE TITLE
Update dependencies.txt with the proper pip commands

### ISSUE THREAD

**Issue by Mulukulum** [Sanjeb/Chat-app#3]
I think its pretty stupid that the dependencies file doesn't include the proper pip commands required to install the packages. Currently only the names of the packages are listed.

Listing a possible change here:

```
customtkinter 
pip install customtkinter

tkinter (Update this to tkinter tooltip as tkinter is already part of the stdlib in python)
pip install tkinter-tooltip

mysql.connector
pip install mysql-connector 
pip install mysql-connector-python

MySQLdb
pip install --only-binary :all: mysqlclient
(I had trouble installing this the regular way and it told me I need visual studio build tools for some reason but this command worked)

PIL
pip install Pillow
logging (This is part of the stdlib and should be removed)
```

**Comment by Mulukulum** [comment]
@Sanjeb

**Comment by Sanjeb** [comment]
The dependencies.txt file has been updated. I've removed a few unnecessary libraries (such as MySQLdb which has been causing a lot of issues) and default libraries that come with python.
