### ISSUE TITLE
CRITICAL : SQL Injection Issue in Discard app

### ISSUE THREAD

**Issue by Mulukulum** [Sanjeb/Chat-app#4]
The code uses fstrings to insert the data for the SQL Queries.

while this makes it readable, it also allows for sql injection pretty easily. 

For instance, into the email tab you can enter the following statement
```
3', `user name`= 'Pls Update Discard app security features Muluk can do haxxing on the discard app' WHERE `user id` = 2 # Comment
```

The code to handle the change email function is currently setup as
```
cursor.execute(f"UPDATE `users` SET `email` = '{email}', `user name` = '{username}', `password` = '{password}' WHERE `user id` = {CurrentUserID}")
```
which explains why the previous code snippet worked.

The solution to this would be to use placeholders, usually '?' (incase of sqlite3 which is what i'm familiar with) or acc to the mysql docs  ,their placeholder is '%s'

This ensures that the query itself cannot be modifed in any meaningful way

Hope to see this and #2 closed pretty soon

Example from [MySQL Documentation](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-execute.html)

```
insert_stmt = (
  "INSERT INTO employees (emp_no, first_name, last_name, hire_date) "
  "VALUES (%s, %s, %s, %s)"
)
data = (2, 'Jane', 'Doe', datetime.date(2012, 3, 23))
cursor.execute(insert_stmt, data)

select_stmt = "SELECT * FROM employees WHERE emp_no = %(emp_no)s"
cursor.execute(select_stmt, { 'emp_no': 2 })
```
In your case, you'd do something like
```
cursor.execute(f"UPDATE `users` SET `email` = %s, `user name` = %s, `password` =  WHERE `user id` = %s ",(email, username, password, CurrentUserID))```

**Comment by Sanjeb** [comment]
Thank you for reporting, We've fixed this bug in the latest version.
