### ISSUE TITLE
edit media handle button persisting in account info after switching

### ISSUE THREAD

**Issue by shyam-k123** [Sanjeb/Chat-app#5]
sometimes there's an extra bit and the edit acccount details button works, sometimes the edit account details button doesn't work
![image (1)](https://user-images.githubusercontent.com/114863924/208177869-e6310b88-ad83-4fc3-9000-2e71f188ced1.png)
![image](https://user-images.githubusercontent.com/114863924/208177874-413696bd-77dd-447d-884e-5378ecb6437b.png)

how to get the issue:
1)go to settings
2)go to other handles
3)click edit media handles and done
4)go back to account info

**Comment by Sanjeb** [comment]
Thank you for reporting the bug, issue has been fixed in v3.0
