### ISSUE TITLE
Edit account details in "Settings" section of the app does not function after clicked once

### ISSUE THREAD

**Issue by Sai-0903** [Sanjeb/Chat-app#7]
![image](https://user-images.githubusercontent.com/119115730/208231989-7e85b677-7ac2-41bd-8792-ac8522304460.png)
the edit account details button does not work after 1 use, you have to leave the settings page and then return to settings page to use it again

**Comment by Sanjeb** [comment]
Thank you for reporting the bug, issue has been fixed in v3.0
